### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/AniViewer#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create `server.js` sign-up and sign-in post requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a register and log in component 
- [x] Update component to fetch requests for sign-up and sign-in post requests
