### ISSUE TITLE
Feature: User can view a list of animes/mangas

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/AniViewer#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kevin-l1/AniViewer/assets/131307476/78607a7e-d681-472c-8804-a59c226e90a7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to fetch anime/manga from the API
- [x] Create navigation header component
- [x] Create a component to display content from API
