### ISSUE TITLE
Feature: User can add ratings and reviews for items

### ISSUE THREAD

**Issue by kevin-l1** [kevin-l1/AniViewer#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kevin-l1/AniViewer/assets/131307476/ac9d42b6-9d27-4c33-b5ed-cf287a700e0c)
![image](https://github.com/kevin-l1/AniViewer/assets/131307476/aa61f130-e283-487d-a485-08b0a335a822)
![image](https://github.com/kevin-l1/AniViewer/assets/131307476/2782b295-9e04-4b32-89d7-bf37857a97fd)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Update page component to add functionality for rating and review buttons
- [ ] Create pop ups when rating or review is clicked
- [ ] Store information from reviews and ratings into user's database
- [ ] Create component that shows all reviewed/rated items
